global using System.Text.Json;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.OpenApi;
global using Microsoft.OpenApi.Models;
global using Newtonsoft.Json;
global using Scalar.AspNetCore;
global using TMS.Server;
global using TMS.Core;
global using TMS.Infrastructure.DataSeeder;
global using TMS.Application.Extensions;
global using TMS.Contract;
global using TMS.Contract.CommunicationModels;
global using TMS.Contract.Entities;
global using TMS.Contract.MediatR.Interfaces;
global using TMS.Infrastructure;
global using TMS.Infrastructure.Data.DbContextTools;
global using TMS.Infrastructure.Helpers;
global using TMS.Infrastructure.Services;
global using TMS.Server.ExtensionMethods;
global using TMS.Server.Helpers;
global using TMS.Server.PermissionsAndRolesConfig;
global using static TMS.Contract.AppPermissions;
global using static TMS.Server.ApiEndPoints;
global using JsonSerializer = System.Text.Json.JsonSerializer;
