global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using System.ComponentModel.DataAnnotations.Schema;
global using AutoMapper;
global using TMS.Core.Entities;
global using TMS.Core.MediatR.Interfaces;
global using TMS.Core.Entities.Interfaces;